{
 "title": "solution",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "LATENCY"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Current RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(locust_requests_current_rps)",
     "legendFormat": "Current RPS"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "percent" }
   ],
   "targets": [
    { "expr": "locust_requests_fail_ratio", "legendFormat": "Error rate" }
   ]
  },
  {
   "title": "Unique users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "users" }
   ],
   "targets": [
    { "expr": "locust_users", "legendFormat": "Users" }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "RMP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "60*sum(locust_requests_current_rps)",
     "legendFormat": "RMP"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "locust_requests_fail_ratio", "legendFormat": "Error rate" }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Latency 95 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "AVG MAX LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time)",
     "legendFormat": "AVG MAX LATENCY"
    }
   ]
  },
  {
   "title": "AVG LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "AVG LATENCY"
    }
   ]
  }
 ]
}